#!/usr/bin/perl -w

use strict;
use warnings;

binmode STDOUT, ":utf8";
use utf8;

use JSON qw(decode_json);

my $baseUrl = 'https://vvopice.zhouba.cz/api';
my $routeGetList = '/posts/list?limit=5&offset=0';

showPosts($baseUrl, $routeGetList);

sub showPosts {
    my $data = decode_json getResponse(shift . shift);
    for my $r (@$data) {
	    my $c = parse($r->{'text'});
	    print "$r->{'inserted'}\t$r->{'title'}\n\n $c\n\n\n";
    }
}

sub getResponse {
	my $url = shift;
	my $query = "wget -qO - \'". $url . "\'";
	$query = `$query`;
}

sub parse {
	my $c = shift =~ s/<br \/>//gr;
}
